# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python - Ибрагимов Даниил

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [5]:
"ada".capitalize() + "lovelace".capitalize() + "was considered the world's first computer programmer."

"AdaLovelacewas considered the world's first computer programmer."

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [6]:
print('|' + '   right side   '.rstrip() + '|')
print('|' + '   left side   '.lstrip() + '|')
print('|' + '   both sides   '.strip() + '|')

|   right side|
|left side   |
|both sides|


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [7]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code
s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [18]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

##your code
l = s1.split('#')

5. Полученный массив строк склеить через пробел (★☆☆)

In [9]:
' '.join(list)

'Holy cow, Rick! I didn’t know hanging out with you was making me smarter!'

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [10]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

##your code
for num, person in personal_data.items():
    print('{}(age {}) is a {}'.format(person[0], person[1], person[2]))


Ann(age 29) is a Artist
Leo(age 54) is a Programmer
Tiffany(age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [12]:
def is_leap_year(year : int):
    if(((year % 4 == 0) & (year % 100 != 0)) | (year % 400 == 0)):
        print('YES')
    else:
        print('NO')

year = int(input('Введите номер'))
is_leap_year(year=year)

YES


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [14]:
words = ['Not', 'my', 'cup', 'of', 'tea']

##your code
dict([(i, words[i]) for i in range(len(words))])

{0: 'Not', 1: 'my', 2: 'cup', 3: 'of', 4: 'tea'}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [15]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

##your code
dogs_value = dogs.copy()
dogs_index = dogs.copy()
dogs_value.remove('australian cattle dog')
dogs_index.pop(1)

print(dogs)
print(dogs_value)
print(dogs_index)


['border collie', 'australian cattle dog', 'labrador retriever']
['border collie', 'labrador retriever']
['border collie', 'labrador retriever']


10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [21]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

##your code
[x.upper() for x in dogs[2:5]]

['AUSTRALIAN', 'CATTLE', 'DOG']

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [22]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

##your code
for key, value in pets.items():
  print("Name: {}, kind: {}, owner: {}, vaccinated: {}".format(key, value['kind'], value['owner'], value['vaccinated']))

Name: willie, kind: dog, owner: eric, vaccinated: True
Name: walter, kind: cockroach, owner: eric, vaccinated: False
Name: peso, kind: dog, owner: chloe, vaccinated: True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [23]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code
intersection = b.intersection(a)
if a == intersection:
  print(True)
else:
  print(False)

True


13. Объединить несколько множеств (★☆☆)

In [24]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])

##your code
union = a.union(b, c)
print(union)

{2, 35, 3, 5, 6, 4, 8, 10}


14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [25]:
print(b.intersection(a))
print(b.intersection(c))

{35, 5, 6}
{35, 4, 5}


15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [26]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code
print(a ^ b)

{1, 2, 6, 7}


16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

### os, sys, datetime

In [70]:
import os,sys

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [63]:
!mkdir gifs
!touch gifs/gif1.gif
!touch gifs/gif2.gif
!touch gifs/gif3.gif

In [65]:
!find . -type f -name «*.gif» -path ./gifs

18. Создать папку с названием temp и удалить её (★☆☆)

In [68]:
!mkdir temp

In [69]:
!rm -r temp

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [71]:
os.environ

environ{'ELECTRON_RUN_AS_NODE': '1',
        'SHELL': '/bin/bash',
        'SESSION_MANAGER': 'local/daniil-lolypop:@/tmp/.ICE-unix/616,unix/daniil-lolypop:/tmp/.ICE-unix/616',
        'WINDOWID': '79691786',
        'SNAP_REVISION': '111',
        'COLORTERM': 'truecolor',
        'XDG_CONFIG_DIRS': '/home/daniil/.config/kdedefaults:/etc/xdg',
        'LESS': '-R',
        'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0',
        'SNAP_REAL_HOME': '/home/daniil',
        'SNAP_USER_COMMON': '/home/daniil/snap/code/common',
        'LANGUAGE': '',
        '_P9K_TTY': '/dev/pts/1',
        'LESS_TERMCAP_se': '\x1b',
        'LESS_TERMCAP_so': '\x1b',
        'LC_ADDRESS': 'ru_RU.UTF-8',
        'LC_NAME': 'ru_RU.UTF-8',
        'P9K_TTY': 'old',
        'SHELL_SESSION_ID': 'e191459cb82f4010bd7de7c6593bc42a',
        'SNAP_INSTANCE_KEY': '',
        'DESKTOP_SESSION': 'plasma',
        'LC_MONETARY': 'ru_RU.UTF-8',
        'GDK_PIXBUF_MODULE_FILE': '/home/daniil/snap/code/c

20. Как игнорировать warrnings?

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

In [72]:
from datetime import date
from datetime import time
from datetime import datetime
from datetime import timedelta

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [73]:
print(date.today())
print(date.today() - timedelta(days=1))
print(date.today() - timedelta(days=-1))

2022-11-07
2022-11-06
2022-11-08


22. Вывести день недели сегодняшней даты (★☆☆)

In [74]:
wd = date.today().weekday()

days= ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
print("Today is " + days[wd])

Today is monday


23. Получить список дат за предыдущую неделю (★★☆)

In [75]:
for day in range(1,8):
  print(date.today() - timedelta(days=day))

2022-11-06
2022-11-05
2022-11-04
2022-11-03
2022-11-02
2022-11-01
2022-10-31


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [77]:
print(datetime.now().strftime("%c"))

Mon Nov  7 00:10:35 2022


25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [76]:
wd = date.today().weekday()

if wd!=0:
  print(date.today() - timedelta(days=wd))
else:
  print(date.today() - timedelta(days=7))

2022-10-31


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [1]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [29]:
np.size(np.zeros(10))

10

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [30]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [31]:
array = np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [32]:
array = np.array([1, 2, 3])
array = array[::-1]
print(array)

[3 2 1]


6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [33]:
arr = np.arange(0,9)
arr = arr.reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [34]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4]),)


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [35]:
matrix = np.random.random((10, 10))
print(matrix.min())
print(matrix.max())
print(matrix.mean())

0.003932552299904302
0.9861361763578779
0.5105776567226534


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [36]:
mat = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [37]:
m = np.random.random((5, 5))
m = (m - m.mean()) / m.std()
print(m)

[[ 1.15869266 -1.30849869  0.52905436 -1.11690815  0.46867644]
 [-0.86052016  0.02814376 -1.11700666  0.14573578 -0.55368015]
 [ 1.3720757   1.4441943   0.51211023  1.50371403  1.14353954]
 [-1.4891755   1.05289169  1.14284607 -1.77160692 -0.4839663 ]
 [-0.60241538  0.11300157  0.26539006 -0.34742731 -1.22886096]]


11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [38]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])
i = np.intersect1d(a, b)
print(i)

[3]


12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [9]:
import math

ls = np.linspace(1, 10)
result1 = []
for num in ls:
    result1.append(int(num))
print(result1)

result2 = []
for num in ls:
    result2.append(math.trunc(num))
print(result2)

str_result3 = []
for num in ls:
    str_result3.append(str(num).split('.')[0])
result3 = [int(i) for i in str_result3]
print(result3)

[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10]
[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10]
[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [39]:
r = np.random.random(10)
r.sort()
print(r)

[0.02652069 0.03495585 0.14055604 0.36590099 0.47935175 0.55252428
 0.69193726 0.74580132 0.90493092 0.9929126 ]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [40]:
a = np.random.random(10)
b = np.random.random(10)
print(np.allclose(a, b))
print(np.array_equal(a, b))

False
False


15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [47]:
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = -1
print(vec)

[0.97325512 0.1690341  0.76622924 0.82398965 0.26181282 0.80340114
 0.16179312 0.33753668 0.31107335 0.76603304]
[-1.          0.1690341   0.76622924  0.82398965  0.26181282  0.80340114
  0.16179312  0.33753668  0.31107335  0.76603304]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [36]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index = Z[round(v)]

print(v)
print(Z[index])

49.70308481935108
50


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [42]:
matrix = np.reshape([round(np.random.random()*100) for i in range(25)],(5,5))
m_xy = matrix.shape 
str_sum = 0
for i in range(m_xy[0]):
  for j in range(m_xy[1]):
    str_sum = str_sum + matrix[i][j]
  
  str_sum = str_sum/m_xy[1]
  print(f"среднее для элементов строки {i} в матрице равно {str_sum}")
  str_sum = 0


среднее для элементов строки 0 в матрице равно 61.2
среднее для элементов строки 1 в матрице равно 37.2
среднее для элементов строки 2 в матрице равно 67.4
среднее для элементов строки 3 в матрице равно 32.8
среднее для элементов строки 4 в матрице равно 58.4


18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849