In [ ]:
import numpy as np
import pandas as pd

# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [ ]:
s1 = "ada"
s2 = "lovelace"
s3 = "was considered the world's first computer programmer."
s1=s1.capitalize()
s2=s2.capitalize()
result = s1+s2+s3
print(result)

AdaLovelacewas considered the world's first computer programmer.


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [2]:
string = ",,,,,rrttgg..   ...banana....rrr"
print(string.strip(" ,.grt")) # удаление произвольных символов

banana


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [ ]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code
s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"
s1 = s1.split("#")
##your code
print(s1)


['Holy', 'cow,', 'Rick!', 'I', 'didn’t', 'know', 'hanging', 'out', 'with', 'you', 'was', 'making', 'me', 'smarter!']


5. Полученный массив строк склеить через пробел (★☆☆)

In [ ]:
newstr = str()
for i in s1:
  newstr += i+' '
print(newstr)

Holy cow, Rick! I didn’t know hanging out with you was making me smarter! 


6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

##your code
for key,value in personal_data.items():
  print(f"Name = {value[0]}, Age = {value[1]}, is Job = {value[2]}")

Name = Ann, Age = 29, is Job = Artist
Name = Leo, Age = 54, is Job = Programmer
Name = Tiffany, Age = 43, is Job = Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [ ]:
year = int(input())
if (year % 4 == 0 and year%100 != 0) or (year%400 == 0):
    print("Высокосный")
else:
    print("Обычный")

14
Обычный


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [5]:
words = ['Not', 'my', 'cup', 'of', 'tea']
dct = dict()
j=0
##your code
for i in words:
  dct[f'{i}']=j
  j=j+1

dct.items()

dict_items([('Not', 0), ('my', 1), ('cup', 2), ('of', 3), ('tea', 4)])

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

##your code
dogs.pop(1)

'australian cattle dog'

In [ ]:
dogs

['border collie', 'labrador retriever']

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [ ]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

##your code
[x.upper() for x in dogs[2:5]]

['AUSTRALIAN', 'CATTLE', 'DOG']

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

##your code
for key,value in pets.items():
  print(key,value['kind'],value['owner'], value['vaccinated'])

willie dog eric True
walter cockroach eric False
peso dog chloe True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [ ]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code
print(a.issubset(b))
print(b.issubset(a))

True
False


13. Объединить несколько множеств (★☆☆)

In [ ]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])


total_set = set()
##your code
total_set = a.union(b)
total_set = total_set.union(c)
total_set

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [ ]:
print(b.intersection(a))
print(b.intersection(c))

{35, 5, 6}
{35, 4, 5}


15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [ ]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code
a.symmetric_difference(b)

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [ ]:
dct = {
    "Adrianov": {
        "age": 15,
        "debt": 2000,
        "occupation": "artist"
        },
    "Karpushev": {
        "age": 25,
        "debt": 23000,
        "occupation": "worker"
        },
    "Mishunin": {
        "age": 22,
        "debt": 500,
        "occupation": "IT"
        }
}

In [ ]:
myset = set()

for key,value in dct.items():
  myset.add(value['occupation'])

print(f'Уникальных профессий = {len(myset)} штук')

myset.clear()

Уникальных профессий = 3 штук


In [ ]:
import json
  
with open("data.json", "w") as myfile:
    json.dump(dct, myfile)

### os, sys, datetime

In [ ]:
import os,sys

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [ ]:
!mkdir gifs

In [ ]:
!cd gifs/
!touch gif1.gif
!touch gif2.gif
!touch gif3.gif
!touch gif4.gif

In [ ]:
!find . -type f -name «*.gif»

18. Создать папку с названием temp и удалить её (★☆☆)

In [ ]:
!mkdir temp
!rm -rf temp

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [ ]:
os.environ

environ{'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1',
        'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2',
        'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2',
        'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
        'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2',
        'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19',
        'CLOUDSDK_PYTHON': 'python3',
        'LANG': 'en_US.UTF-8',
        'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1',
        'HOSTNAME': '9d647ed4c8c9',
        'OLDPWD': '/',
        'CLOUDSDK_CONFIG': '/content/.config',
        'NV_LIBNPP_VERSION': '11.3.2.152-1',
        'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1',
        'NVIDIA_VISIBLE_DEVICES': 'all',
        'NV_NVPROF_VERSION': '11.2.152-1',
        'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1',
        'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"de

20. Как игнорировать warrnings?

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

In [7]:
from datetime import date
from datetime import time
from datetime import datetime
from datetime import timedelta

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [ ]:
print(date.today())
print(date.today() - timedelta(days=1)) # вчера
print(date.today() - timedelta(days=-1)) # завтра


2022-10-30
2022-10-29
2022-10-31


22. Вывести день недели сегодняшней даты (★☆☆)

In [ ]:
wd = date.today().weekday()

days= ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
print("Today is day number %d" % wd)
print("which is a " + days[wd])

Today is day number 6
which is a sunday


23. Получить список дат за предыдущую неделю (★★☆)

In [8]:
for day in range(1,8):
  print(date.today() - timedelta(days=day))


2022-11-05
2022-11-04
2022-11-03
2022-11-02
2022-11-01
2022-10-31
2022-10-30


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [ ]:
print(datetime.now().strftime("%c"))

Sun Oct 30 08:42:41 2022


25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [ ]:
wd = date.today().weekday()

if wd!=0:
  print(date.today() - timedelta(days=wd))
else:
  print(date.today() - timedelta(days=7))

2022-10-24


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [ ]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [ ]:
v = np.zeros(10)

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [ ]:
np.size(v)

10

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [ ]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [ ]:
vv = np.arange(start=10,stop=50)
vv

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [ ]:
vv=vv[::-1]

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [ ]:
matrix = np.arange(start=0,stop=9).reshape(3,3)

In [ ]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [ ]:
import random

In [ ]:
matrix = np.reshape([round(random.random()*100) for i in range(100)],(10,10))

In [ ]:
matrix

array([[34, 65, 20, 16, 35, 47, 67, 77, 13, 54],
       [69, 95, 35, 19, 64, 98, 94, 26, 72, 53],
       [17, 80, 65, 77, 35, 61, 67, 11,  7, 64],
       [ 2, 91, 58, 90, 83, 58, 10, 57,  6,  1],
       [36, 44, 62, 89, 12, 58, 97, 43, 25, 47],
       [86, 88, 17, 69, 11, 64, 21, 41, 98, 48],
       [96, 95, 66, 10, 39, 39, 85,  9,  7, 35],
       [ 2, 65, 10, 81, 44,  0, 14, 24, 43, 58],
       [23, 25, 61, 41, 51, 29, 37, 50, 63, 67],
       [38, 47, 15, 17, 66, 28, 31,  5, 32, 51]])

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [ ]:
matrix = np.zeros((8,8), dtype = int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [ ]:
matrix = np.reshape([round(random.random()*100) for i in range(25)],(5,5))

In [ ]:

mean = matrix.mean()
std = matrix.std()
print(mean)
for el in matrix:
  el = (el - mean)/std
  print(el)

52.76
[-0.48968699 -1.17233614 -0.85376654  1.10316103  0.28398205]
[ 1.05765108  0.51153176 -0.94478642  2.10437978  1.2852008 ]
[-0.53519693 -2.08253501 -0.12560744  0.78459142 -0.17111739]
[-1.39988586 -0.26213727  0.10194227 -0.21662733  1.51275052]
[-1.26335603 -0.3986671   1.10316103  0.46602182 -0.3986671 ]


11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [ ]:
np.intersect1d([x for x in range(10)],[x for x in range(15)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [21]:
import numpy as np
import math
# 1
lst = np.linspace(1,10)
print("numpy array is: \n",lst)
result = list()
for el in lst:
  result.append(math.floor(el))

print(result)


# 2
lst2 = [k+k*0.1 for k in range(10)]
result.clear()
print(f"python list is: \n {lst2}")
for e in lst2:
  result.append(int(e))

print(result)


# 3

lst3 = [k+k*0.1 for k in range(10)]
result.clear()
print("python list3 is: ",lst3)
for e in lst3:
  result.append(e//1)

print(result)


numpy array is: 
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10]
python list is: 
 [0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
python list3 is:  [0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [ ]:
vec = [random.randint(1,100) for x in range(10)]
type(vec)

list

In [ ]:
for n in range(len(vec)-1, 0, -1):
  for i in range(n):
      if vec[i] > vec[i + 1]:
        vec[i], vec[i + 1] = vec[i + 1], vec[i]       
  


print(vec)



[4, 8, 35, 56, 62, 65, 75, 85, 95, 99]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [ ]:
np.array_equal([random.randint(1,100) for x in range(10)],[random.randint(1,100) for x in range(10)])

False

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [ ]:
vec = [random.randint(1,100) for x in range(10)]


In [ ]:
vec[np.argmax(vec)]=-1

In [ ]:
vec

[47, -1, 18, 53, 66, 23, 60, 11, 69, 89]

16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100) # данное число
print(Z)
print("*******")
print(v)
print("*******")

delta = 10000
for i in range(len(Z)-1):
  if Z[i]-v<abs(delta):
    delta = v-Z[i]
    index =  i


print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
*******
23.978530068659186
*******
24


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [ ]:
matrix = np.reshape([round(random.random()*100) for i in range(25)],(5,5))
matrix

array([[10, 57, 22, 40, 33],
       [37, 92, 52,  8,  6],
       [80,  0, 64, 34, 71],
       [57,  5, 21, 59, 63],
       [95, 42, 28,  6, 51]])

In [ ]:
m_xy = matrix.shape 
str_sum = 0
for i in range(m_xy[0]):
  for j in range(m_xy[1]):
    str_sum = str_sum + matrix[i][j]
  
  str_sum = str_sum/m_xy[1]
  print(f"среднее для элементов строки {i} в матрице равно {str_sum}")
  str_sum = 0


среднее для элементов строки 0 в матрице равно 32.4
среднее для элементов строки 1 в матрице равно 39.0
среднее для элементов строки 2 в матрице равно 49.8
среднее для элементов строки 3 в матрице равно 41.0
среднее для элементов строки 4 в матрице равно 44.4


In [ ]:
# проверка
10+57+22+40+33 # 162
162/5

32.4

18. Посчитать среднее со скользящим окном над массивом (★★★)


<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849